# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fc23d50f14d724f943111f231db3ea75d518b98e71b64d7c96b37af3901b284fd2602be63e8b8e85e9dac5873e18f1b9caa8f8e9fa4bbd7d77ab9f65e422a16
  rollbar_access_token: ''
  aws:
    access_key_id: ''
    secret_access_key: ''
    region: ''
    bucket: ''
  smtp:
    server: ''
    port: ''
    domain: ''
    address: ''
    username: ''
    password: ''
  notification_address: ''

test:
  secret_key_base: 29fef41dcb8d6df60537fb3287d2d0fc5080d1786708b06628feecefa344c300e896753912f00169300f4318ac8b64ea33aa069d7c36f35baa7c42ab926aa20d
  rollbar_access_token: ''
  aws:
    access_key_id: ''
    secret_access_key: ''
    region: ''
    bucket: ''
  smtp:
    server: ''
    port: ''
    domain: ''
    address: ''
    username: ''
    password: ''
  notification_address: ''

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  rollbar_access_token: <%= ENV["ROLLBAR_ACCESS_TOKEN"] %>
  aws:
    access_key_id: <%= ENV["S3_ACCESS_KEY_ID"] %>
    secret_access_key: <%= ENV["S3_SECRET_ACCESS_KEY"] %>
    region: <%= ENV["S3_REGION"] %>
    bucket: <%= ENV["S3_BUCKET"] %>
  smtp:
    server: <%= ENV["SMTP_SERVER"] %>
    port: <%= ENV["SMTP_PORT"] %>
    domain: <%= ENV["SMTP_DOMAIN"] %>
    address: <%= ENV["SMTP_ADDRESS"] %>
    username: <%= ENV["SMTP_USERNAME"] %>
    password: <%= ENV["SMTP_PASSWORD"] %>
  notification_address: <%= ENV["NOTIFICATIO_ADDRESS"] %>
